In [8]:
## Shape : it is used to get the row and cols in a matrix
## ndim : to know the no of dimensions
## size : to set the number elements
## dtype : to know the datatype of an array
## nbytes : to get memory of arr in bytes

import numpy as np 
arr = np.array([[1,2],[1,2],[3,4]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.nbytes)


(3, 2)
2
6
int64
48


In [13]:
##  Zeros : it gives 4 cols and 3 rows with zeros
import numpy as np
arr=np.zeros((4,3))
print(arr)

##  to get unique integer
arr=np.full((5,2),7)
print(arr)

## to fill with random data in blw range in rows and cols
arr=np.random.randint(1,10 ,size=(3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]]
[[8 5 5]
 [1 6 6]
 [4 3 2]]


In [18]:
## identity matrix: To fill with the identity matrix which have diagonals and remaining zeros
import numpy as np
arr = np.eye(5)
print(arr)
## arange : to get some range of values in an arr
arr = np.arange(0,20,2)
print(arr)
## random.rand : to fill some random 16digit decimal data in r&c
arr = np.random.rand(2,3)
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[[0.15702186 0.38973825 0.61723816]
 [0.70006683 0.52361006 0.13713313]]
