In [11]:
import numpy as np
marks=np.array([35,40,48,55,70])
total_marks=np.sum(marks)
print(total_marks)
average_marks=np.mean(marks)
print(average_marks)
min_marks=np.min(marks)
max_marks=np.max(marks)
print(min_marks,"\n",max_marks)
standird_deviation=np.std(marks)
print(standird_deviation)

248
49.6
35 
 70
12.273548794053006


In [29]:
import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
shape_matrix=np.shape(matrix)
print(shape_matrix)
mat_dimension=np.ndim(matrix)
print(mat_dimension)
mat_datatype=matrix.dtype
print(mat_datatype)
mat_size=matrix.size
print(mat_size)
middle_ele=matrix[1,1]
print(middle_ele)
fr=matrix[0]
print(fr)
lc=matrix[:,-1]
print(lc)




(3, 3)
2
int64
9
5
[1 2 3]
[3 6 9]


In [ ]:
import numpy as np
arr=np.zeros((4,3))
print(arr)

arr=np.ones((4,3))
print(arr)

arr=np.eye(5)
print(arr)

arr = np.arange(10,50,2)
print(arr)

arr=np.linspace(0,1,5)
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0.   0.25 0.5  0.75 1.  ]


In [35]:
import numpy as np

# Original monthly salaries
salaries = np.array([25000, 30000, 40000, 50000])

# 1. Increase each salary by 10% (element-wise operation)
increased_salaries = salaries * 1.10

# 2. Calculate yearly salary (monthly × 12)
yearly_salaries = increased_salaries * 12

# 3. Find employees earning more than 35,000 (boolean indexing)
high_earners = increased_salaries[increased_salaries > 35000]

print("Original Salaries:", salaries)
print("Salaries after 10% increase:", increased_salaries)
print("Yearly Salaries:", yearly_salaries)
print("Employees earning more than 35,000:", high_earners)


Original Salaries: [25000 30000 40000 50000]
Salaries after 10% increase: [27500. 33000. 44000. 55000.]
Yearly Salaries: [330000. 396000. 528000. 660000.]
Employees earning more than 35,000: [44000. 55000.]


In [46]:
import numpy as np

# Generate 12 random integers between 1 and 100
data = np.random.randint(1, 101, 12)

# Reshape into a 3×4 matrix
matrix = data.reshape(3, 4)

print("3x4 Matrix:")
print(matrix)

# Print each row separately (iteration)
print("\nEach row:")
for row in matrix:
    print(row)

# Flatten the matrix back to 1D
flattened = matrix.flatten()
print("\nFlattened array:")
print(flattened)

# Find sum of each row
row_sums = np.sum(matrix,axis=1)
print("\nSum of each row:")
print(row_sums)


3x4 Matrix:
[[55 17 33 49]
 [81 28 63  3]
 [87 56 91 31]]

Each row:
[55 17 33 49]
[81 28 63  3]
[87 56 91 31]

Flattened array:
[55 17 33 49 81 28 63  3 87 56 91 31]

Sum of each row:
[154 175 265]
